version: '3.1'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    build: ./oscarwhiskey
    command: python /code/manage.py runserver 0.0.0.0:80
    volumes:
      - ./oscarwhiskey:/code:delegated
    ports:
      - "8000:80"
      - "9000:9000"
    links:
      - db
    environment:
      DATABASE_URL: 'postgres://postgres@db:5432/postgres'
      ENVIRONMENT: 'development'
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgres-data:
